server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/excel
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB